# -*- coding: utf-8 -*-
"""Mini_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihYVJOOFHIb_aVzFOFZICXK6NhQ1MSIY
"""

import pandas as pd

def extract():
  orders_df = pd.read_csv('raw_orders_project.csv')
  customers_df = pd.read_csv('raw_customers.csv')
  products_df = pd.read_csv('raw_products.csv')
  return orders_df, customers_df, products_df

def clean_customers(customers_df):
    """Clean the customers dataset and add age_group."""
    customers_df = customers_df.copy()

    # Standardize column names
    customers_df.columns = [col.strip().lower() for col in customers_df.columns]

    # Remove duplicate customer rows
    customers_df = customers_df.drop_duplicates()

    # Fill missing email with a placeholder value
    customers_df["email"] = customers_df["email"].fillna(
        customers_df["customer_name"].str.lower().str.replace(" ", "_") + "@unknown.com"
    )

    # Fill missing age with median age
    median_age = round(customers_df["age"].median())
    customers_df["age"] = customers_df["age"].fillna(median_age).astype(int)

    # Fill missing city with Unknown
    customers_df["city"] = customers_df["city"].fillna("Unknown")

    # Create age_group column
    def get_age_group(age):
        if age < 30:
            return "Under 30"
        elif age <= 40:
            return "30 to 40"
        return "Over 40"

    customers_df["age_group"] = customers_df["age"].apply(get_age_group)

    return customers_df

def clean_products(products_df):

  products_df = products_df.copy()
  # standarized the columns
  products_df.columns = [col.strip().lower() for col in products_df]

  #remove the duplicates
  products_df = products_df.drop_duplicates()

  #Fill Missing Category
  products_df['category'] = products_df['category'].fillna('Electronics')

  #Convert product names inti title case
  products_df['product_name'] = products_df['product_name'].str.title()

  return products_df

def transform(orders_df, customers_df, products_df):

  orders_df = orders_df.copy()

  #standarized the columns
  orders_df.columns = [col.strip().lower() for col in orders_df]

  #Remove the duplicates
  orders_df = orders_df.drop_duplicates()

  #Fill the missing the customer id
  orders_df = orders_df.dropna(subset=['customer_id'])

  #Fill the missing order_date
  orders_df = orders_df.dropna(subset=['order_date'])

  #Fill missing unit price(important below part)
  # Remove duplicate product rows
  products_df = products_df.drop_duplicates(subset=["product_id"])

  # Create product_id -> unit_price lookup
  product_price_map = products_df.set_index("product_id")["unit_price"]

  # Fill missing unit_price using lookup
  orders_df["unit_price"] = orders_df["unit_price"].fillna(
    orders_df["product_id"].map(product_price_map))

  # Converting numerical columns
  orders_df['quantity'] = orders_df['quantity'].astype(int)
  orders_df["unit_price"] = orders_df["unit_price"].astype(float)
  orders_df["discount"] = orders_df["discount"].astype(float)

  # Add total_amount column
  orders_df["total_amount"] = (
      orders_df["quantity"] * orders_df["unit_price"]) - orders_df["discount"]

  return orders_df

def load(orders_df, customers_df, products_df):
  orders_df.to_csv("stg_orders.csv", index=False)
  customers_df.to_csv("stg_customers.csv", index=False)
  products_df.to_csv("stg_products.csv", index=False)

def main():
    orders_df, customers_df, products_df = extract()

    customers_clean = clean_customers(customers_df)
    products_clean = clean_products(products_df)

    orders_clean = transform(
        orders_df,
        customers_clean,
        products_clean
    )

    load(
        orders_clean,
        customers_clean,
        products_clean
    )

    print("ETL completed successfully.")

if __name__ == "__main__":
    main()

"""###1.Import Libraries for SQLite

"""

import sqlite3
import pandas as pd

"""###2.Connect to SQLite database &  Read staging CSV files

"""

conn = sqlite3.connect('ecommerce_de.db')
cursor = conn.cursor()

#Read staging CSV files
stg_orders = pd.read_csv("stg_orders.csv")
stg_customers = pd.read_csv("stg_customers.csv")
stg_products = pd.read_csv("stg_products.csv")

"""###3.Load staging CSVs into SQLite"""

stg_orders.to_sql("stg_orders", conn, if_exists="replace", index=False)
stg_customers.to_sql("stg_customers", conn, if_exists="replace", index=False)
stg_products.to_sql("stg_products", conn, if_exists="replace", index=False)

print("Staging tables loaded into SQLite successfully.")

print(pd.read_sql("SELECT * FROM stg_customers", conn))
print(pd.read_sql("SELECT * FROM stg_products", conn))
print(pd.read_sql("SELECT * FROM stg_orders", conn))

"""##CREATE STAR SCHEMA

###Create dim_customers
"""

cursor.execute("DROP TABLE IF EXISTS dim_customers")

cursor.execute("""
CREATE TABLE dim_customers AS
SELECT DISTINCT
    customer_id,
    customer_name,
    city,
    country,
    age_group
FROM stg_customers
""")

cursor.execute("DROP TABLE IF EXISTS dim_products")

cursor.execute("""
CREATE TABLE dim_products AS
SELECT DISTINCT
    product_id,
    product_name,
    category,
    sub_category,
    brand
FROM stg_products
""")

cursor.execute("DROP TABLE IF EXISTS dim_date")

cursor.execute("""
CREATE TABLE dim_date AS
SELECT DISTINCT
    CAST(strftime('%Y%m%d', order_date) AS INTEGER) AS date_id,
    order_date AS full_date,
    CAST(strftime('%Y', order_date) AS INTEGER) AS year,
    CAST(strftime('%m', order_date) AS INTEGER) AS month,
    CASE strftime('%m', order_date)
        WHEN '01' THEN 'January'
        WHEN '02' THEN 'February'
        WHEN '03' THEN 'March'
        WHEN '04' THEN 'April'
        WHEN '05' THEN 'May'
        WHEN '06' THEN 'June'
        WHEN '07' THEN 'July'
        WHEN '08' THEN 'August'
        WHEN '09' THEN 'September'
        WHEN '10' THEN 'October'
        WHEN '11' THEN 'November'
        WHEN '12' THEN 'December'
    END AS month_name,
    CASE
        WHEN CAST(strftime('%m', order_date) AS INTEGER) BETWEEN 1 AND 3 THEN 'Q1'
        WHEN CAST(strftime('%m', order_date) AS INTEGER) BETWEEN 4 AND 6 THEN 'Q2'
        WHEN CAST(strftime('%m', order_date) AS INTEGER) BETWEEN 7 AND 9 THEN 'Q3'
        ELSE 'Q4'
    END AS quarter,
    CASE strftime('%w', order_date)
        WHEN '0' THEN 'Sunday'
        WHEN '1' THEN 'Monday'
        WHEN '2' THEN 'Tuesday'
        WHEN '3' THEN 'Wednesday'
        WHEN '4' THEN 'Thursday'
        WHEN '5' THEN 'Friday'
        WHEN '6' THEN 'Saturday'
    END AS day_of_week,
    CASE
        WHEN strftime('%w', order_date) IN ('0', '6') THEN 'Yes'
        ELSE 'No'
    END AS is_weekend
FROM stg_orders
""")

cursor.execute("DROP TABLE IF EXISTS fact_orders")

cursor.execute("""
CREATE TABLE fact_orders AS
SELECT
    order_id,
    customer_id,
    product_id,
    CAST(strftime('%Y%m%d', order_date) AS INTEGER) AS date_id,
    store_id,
    quantity,
    unit_price,
    discount,
    total_amount
FROM stg_orders
""")

"""###Commit changes"""

conn.commit()
print("Star schema created successfully.")

print(pd.read_sql("SELECT * FROM dim_customers", conn))
print(pd.read_sql("SELECT * FROM dim_products", conn))
print(pd.read_sql("SELECT * FROM dim_date", conn))
print(pd.read_sql("SELECT * FROM fact_orders", conn))

"""#BUSINESS QUESTIONS
##1. Which customer spent the most in total?
"""

query1 = """
SELECT
    c.customer_id,
    c.customer_name,
    ROUND(SUM(f.total_amount), 2) AS total_spent
FROM fact_orders f
JOIN dim_customers c
    ON f.customer_id = c.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spent DESC
LIMIT 1
"""

print(pd.read_sql(query1, conn))

"""##2.Which product generates the highest total revenue?"""

query2 = """
SELECT
    p.product_id,
    p.product_name,
    ROUND(SUM(f.total_amount), 2) AS total_revenue
FROM fact_orders f
JOIN dim_products p
    ON f.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
LIMIT 1
"""

print(pd.read_sql(query2, conn))

"""##3.How does revenue trend week by week across January?"""

query3 = """
SELECT
    strftime('%W', d.full_date) AS week_number,
    ROUND(SUM(f.total_amount), 2) AS weekly_revenue
FROM fact_orders f
JOIN dim_date d
    ON f.date_id = d.date_id
WHERE d.month = 1
  AND d.year = 2024
GROUP BY strftime('%W', d.full_date)
ORDER BY week_number
"""

print(pd.read_sql(query3, conn))

"""##4.Which store has the highest average order value?"""

query4 = """
SELECT
    store_id,
    ROUND(AVG(total_amount), 2) AS avg_order_value
FROM fact_orders
GROUP BY store_id
ORDER BY avg_order_value DESC
LIMIT 1
"""

print(pd.read_sql(query4, conn))

"""##5.What percentage of orders have a discount applied?"""

query5 = """
SELECT
    ROUND(
        SUM(CASE WHEN discount > 0 THEN 1.0 ELSE 0 END)
        / COUNT(*) * 100, 2
    ) AS discount_order_percentage
FROM fact_orders;
"""

print(pd.read_sql(query5,conn))

